### ISSUE TITLE
:heart:

### ISSUE THREAD

**Issue by semmons99** [teamsnap/pipe-ruby#1]
Really love it @dmvt 

Three questions.
1. Any reason we should support Ruby < 2.1.x? We use keyword args that are only compatible w/ 2.1.x and greater.
2. Version is kept under `lib/pipe/ruby/version.rb` guessing that's bundler's doing. Can it just be moved to `lib/pipe/version.rb` and namespaced as `Pipe::VERSION`?
3. I brought in the [inflecto](https://github.com/mbj/inflecto) gem for teamsnap_rb. It's proven very nice and lightweight if you don't want to carry around your own inflections. I'm actually working with the maintainer to potentially take it over.

**Comment by dmvt** [comment]
1. Adding the version requirement now. I don't think there's any reason to support older versions.
2. We could certainly do this. I'll add that into this morning's PR.
3. I love inflecto and am excited that you'll be potentially taking it over. For this purpose, I wanted to match the Rails version of `constantize` as to not confuse people. They are slightly different in their lookup approach I believe.

**Comment by semmons99** [comment]
:+1:
