### ISSUE TITLE
Error handling prevents true exception from being caught

### ISSUE THREAD

**Issue by ryanwi** [teamsnap/pipe-ruby#6]
Since pipe-ruby combines the ReducerError with the actual exception being raise, it prevents the error from being rescued as its not a known type. This comes into play particularly with [Sinatra's error handling](http://www.sinatrarb.com/intro.html#Error), when you can have an `error` for a custom error. If the actual error is `Namespace::NotFound` and you have a custom error handler in sinatra, it will not be executed because the error Sinatra gets is `Pipe::ReducerError::NotFound`.  Alternatively, you cannot have a custom error for `Pipe::ReducerError::NotFound` because it doesn't exist until the error is raised, causing Sinatra to complain when starting up.

**Comment by dmvt** [comment]
Interesting... How do you feel about not re-writing the error class? It hasn't been working out all that well for me either...

**Comment by ryanwi** [comment]
I feel good about that, but wanted to make sure you didn't need to re-write it still.

**Comment by coreycondardo** [comment]
Ran into this issue today (thanks for pointing the issue out to me @ryanwi).

My experience was if an error pops inside the pipe, I get:
```
<Pipe::HandlerError::NoMethodError: undefined method `notice_error' for nil:NilClass [{:method=>:fet...6d896bb6c8", :type=>"divisions.plan_change"}, :division_id=>1, :plan_type=>"foo"}>}, NoMethodError]>
```
When setting the `config` to `:raise_on_error => true` I get:
```
#<Pipe::ReducerError::PlanTypeNotFoundError: PlanTypeMapper::PlanTypeNotFoundError [{:method=>:fetch_...isions.plan_change"}, :division_id=>1, :plan_type=>"foo"}>}, PlanTypeMapper::PlanTypeNotFoundError]>
```
Is there a use case for the default behavior to be the first type of error? It doesn't provide the context I need, but this is my first time really dealing with the pipe :).

To work around it I need to either set the config everywhere pipe is used, which is a pain.
